export enum ErrorEnum {
  DEFAULT = '0:Unknown error',
  SERVER_ERROR = '500: The service is busy, please try again later',

  SYSTEM_USER_EXISTS = '1001: System user already exists',
  INVALID_VERIFICATION_CODE = '1002: The verification code is incorrectly filled in',
  INVALID_USERNAME_PASSWORD = '1003: The username and password are incorrect',
  NODE_ROUTE_EXISTS = '1004: Node route already exists',
  PERMISSION_REQUIRES_PARENT = '1005: Permission must include parent node',
  ILLEGAL_OPERATION_DIRECTORY_PARENT = '1006: Illegal operation: This node only supports directory type parent nodes',
  ILLEGAL_OPERATION_CANNOT_CONVERT_NODE_TYPE = '1007: Illegal operation: node type cannot be converted directly',
  ROLE_HAS_ASSOCIATED_USERS = '1008: There are associated users for this role, please delete the associated users first',
  DEPARTMENT_HAS_ASSOCIATED_USERS = '1009: There are associated users in this department, please delete the associated users first',
  DEPARTMENT_HAS_ASSOCIATED_ROLES = '1010: There are associated roles in this department, please delete the associated roles first',
  PASSWORD_MISMATCH = '1011: The old password is inconsistent with the original password',
  LOGOUT_OWN_SESSION = '1012: If you want to log out, you can exit in the upper right corner',
  NOT_ALLOWED_TO_LOGOUT_USER = '1013: This user is not allowed to log out',
  PARENT_MENU_NOT_FOUND = '1014: Parent menu does not exist',
  DEPARTMENT_HAS_CHILD_DEPARTMENTS = '1015: This department has sub-departments, please delete the sub-departments first',
  SYSTEM_BUILTIN_FUNCTION_NOT_ALLOWED = '1016: The system\'s built-in functions are not allowed to operate',
  USER_NOT_FOUND = '1017: The user does not exist',
  UNABLE_TO_FIND_DEPARTMENT_FOR_USER = '1018: Unable to find the department to which the current user belongs',
  DEPARTMENT_NOT_FOUND = '1019: The department does not exist',
  DICT_NAME_EXISTS = '1020: A dictionary with the same name already exists',
  PARAMETER_CONFIG_KEY_EXISTS = '1021: Parameter configuration key-value pair already exists',
  DEFAULT_ROLE_NOT_FOUND = '1022: The assigned default role does not exist',

  INVALID_LOGIN = '1101: Invalid login, please log in again',
  NO_PERMISSION = '1102: No permission to access',
  ONLY_ADMIN_CAN_LOGIN = '1103: Not an administrator and cannot log in',
  REQUEST_INVALIDATED = '1104: The current request has expired',
  ACCOUNT_LOGGED_IN_ELSEWHERE = '1105: Your account has been logged in elsewhere',
  GUEST_ACCOUNT_RESTRICTED_OPERATION = '1106: Guest account operation not allowed',
  REQUESTED_RESOURCE_NOT_FOUND = '1107: The requested resource does not exist',

  TOO_MANY_REQUESTS = '1201: The request frequency is too fast, please try again after one minute',
  MAXIMUM_FIVE_VERIFICATION_CODES_PER_DAY = '1202: Send up to 5 verification codes a day',
  VERIFICATION_CODE_SEND_FAILED = '1203: Failed to send verification code',

  INSECURE_MISSION = '1301: Unsafe task, ensure execution by adding @Mission annotation',
  EXECUTED_MISSION_NOT_FOUND = '1302: The executed task does not exist',
  MISSION_EXECUTION_FAILED = '1303: Task execution failed',
  MISSION_NOT_FOUND = '1304: The task does not exist',

  // OSS related
  OSS_FILE_OR_DIR_EXIST = '1401: The currently created file or directory already exists',
  OSS_NO_OPERATION_REQUIRED = '1402: No operation required',
  OSS_EXCEE_MAXIMUM_QUANTITY = '1403: The maximum supported processing quantity has been exceeded',
}
